const influencers = [
  {
    id: 1,
    images: [
      "https://picsum.photos/300/200?random=1",
      "https://picsum.photos/300/200?random=2",
      "https://picsum.photos/300/200?random=3",
      "https://picsum.photos/300/200?random=4",
      "https://picsum.photos/300/200?random=5",
    ],
    profileImg: "https://i.pravatar.cc/150?img=1",
    username: "@amanda_nash",
    name: "Amanda Nash 🍁",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 300,
    followers: "24k",
    following: 231,
  },
  {
    id: 2,
    images: [
      "https://picsum.photos/300/200?random=6",
      "https://picsum.photos/300/200?random=7",
      "https://picsum.photos/300/200?random=8",
      "https://picsum.photos/300/200?random=9",
      "https://picsum.photos/300/200?random=10",
    ],
    profileImg: "https://i.pravatar.cc/150?img=2",
    username: "@robert_ford",
    name: "Robert Ford 😎",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 120,
    followers: "489k",
    following: 987,
  },
  {
    id: 3,
    images: [
      "https://picsum.photos/300/200?random=11",
      "https://picsum.photos/300/200?random=12",
      "https://picsum.photos/300/200?random=13",
      "https://picsum.photos/300/200?random=14",
      "https://picsum.photos/300/200?random=15",
    ],
    profileImg: "https://i.pravatar.cc/150?img=3",
    username: "@camcamcam",
    name: "Cameron Schmidt 🚀",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 450,
    followers: "1.2M",
    following: 321,
  },
  {
    id: 4,
    images: [
      "https://picsum.photos/300/200?random=16",
      "https://picsum.photos/300/200?random=17",
      "https://picsum.photos/300/200?random=18",
      "https://picsum.photos/300/200?random=19",
      "https://picsum.photos/300/200?random=20",
    ],
    profileImg: "https://i.pravatar.cc/150?img=4",
    username: "@luna_life",
    name: "Luna Life 🌿",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 180,
    followers: "76k",
    following: 412,
  },
  {
    id: 5,
    images: [
      "https://picsum.photos/300/200?random=21",
      "https://picsum.photos/300/200?random=22",
      "https://picsum.photos/300/200?random=23",
      "https://picsum.photos/300/200?random=24",
      "https://picsum.photos/300/200?random=25",
    ],
    profileImg: "https://i.pravatar.cc/150?img=5",
    username: "@urban.jay",
    name: "Jason Miller 🤩",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 390,
    followers: "302k",
    following: 654,
  },
  {
    id: 6,
    images: [
      "https://picsum.photos/300/200?random=26",
      "https://picsum.photos/300/200?random=27",
      "https://picsum.photos/300/200?random=28",
      "https://picsum.photos/300/200?random=29",
      "https://picsum.photos/300/200?random=30",
    ],
    profileImg: "https://i.pravatar.cc/150?img=6",
    username: "@nature.elle",
    name: "Elle Green 🍀",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 210,
    followers: "98k",
    following: 187,
  },
  {
    id: 7,
    images: [
      "https://picsum.photos/300/200?random=31",
      "https://picsum.photos/300/200?random=32",
      "https://picsum.photos/300/200?random=33",
      "https://picsum.photos/300/200?random=34",
      "https://picsum.photos/300/200?random=35",
    ],
    profileImg: "https://i.pravatar.cc/150?img=7",
    username: "@focus.finn",
    name: "Finn Carter 🏫",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 95,
    followers: "41k",
    following: 99,
  },
  {
    id: 8,
    images: [
      "https://picsum.photos/300/200?random=36",
      "https://picsum.photos/300/200?random=37",
      "https://picsum.photos/300/200?random=38",
      "https://picsum.photos/300/200?random=39",
      "https://picsum.photos/300/200?random=40",
    ],
    profileImg: "https://i.pravatar.cc/150?img=8",
    username: "@skylar.mov",
    name: "Skylar ❤️‍🔥",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 520,
    followers: "890k",
    following: 1021,
  },
  {
    id: 9,
    images: [
      "https://picsum.photos/300/200?random=41",
      "https://picsum.photos/300/200?random=42",
      "https://picsum.photos/300/200?random=43",
      "https://picsum.photos/300/200?random=44",
      "https://picsum.photos/300/200?random=45",
    ],
    profileImg: "https://i.pravatar.cc/150?img=9",
    username: "@minimal.mia",
    name: "Mia Rose ❤️",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 140,
    followers: "67k",
    following: 244,
  },
  {
    id: 10,
    images: [
      "https://picsum.photos/300/200?random=46",
      "https://picsum.photos/300/200?random=47",
      "https://picsum.photos/300/200?random=48",
      "https://picsum.photos/300/200?random=49",
      "https://picsum.photos/300/200?random=50",
    ],
    profileImg: "https://i.pravatar.cc/150?img=10",
    username: "@astro.alex",
    name: "Alex Nova 🚀",
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 610,
    followers: "1.5M",
    following: 403,
  },

  // --- extra 10 (shorter, same structure) ---
  ...Array.from({ length: 10 }, (_, i) => ({
    id: 11 + i,
    images: Array.from({ length: 5 }, (_, j) =>
      `https://picsum.photos/300/200?random=${51 + i * 5 + j}`
    ),
    profileImg: `https://i.pravatar.cc/150?img=${11 + i}`,
    username: `@creator_${i + 11}`,
    name: `Creator ${i + 11} 😎`,
    bio: "Lifestyle coach and photographer delivering best images online.",
    media: 100 + i * 20,
    followers: `${20 + i * 5}k`,
    following: 150 + i * 10,
  })),
];

export default influencers;